### ISSUE TITLE
amp is a no go on samples

### ISSUE THREAD

**Issue by danielmkarlsson** [danielmkarlsson/SuperClean#24]
Hi.

Try this example:

```
(
Pdef(0,
	Pbind(*[
		type: \cln,
		snd: \mmd,
		dur: 1/8,
		num: 8,
		amp: Pwhite(0.0, 1.0),
	])
).play
)
```

See what you make of it.

**Comment by thresholdpeople** [comment]
Oh I know what this is. I got rid of the \clean_envelope SynthDef which was responsible for setting sample level. I should have a fix.
