### ISSUE TITLE
Adding large samples into RAM

### ISSUE THREAD

**Issue by danielmkarlsson** [danielmkarlsson/SuperClean#31]
When adding large files into RAM it seems to take a while.
This has led to my seeing an error message stating that `Buffer UGen: no buffer data` despite having just seen this in the postwindow:

```
loading 1 sample bank:
egb (5) 
... file reading complete. Required 1767 MB of memory.
```

I suspect that SuperClean is reporting that it has sent the order to add the files to RAM, rather than having received confirmation that the operation has completed. If this is indeed the case then there is some room for improvement here.

**Comment by thresholdpeople** [comment]
I believe you're correct:

https://github.com/danielmkarlsson/SuperClean/blob/0547c89cf03612cef9234d2c6d6daab507fd43ad/Classes/CleanSoundLibrary.sc#L164

This line is a function that actually begins the sample loading process, and immediately after it is the 'file reading complete' post. I'm pretty sure it's as you say, that function isn't actually waiting for the do function that loads samples to finish. 

I wonder if either sticking that 'success' postln further down in the other function, or something along the lines of s.sync would be a simple solution?

**Comment by danielmkarlsson** [comment]
Not exactly fixed so much as changed the wording of the message.
