### ISSUE TITLE
Add updating support to readme

### ISSUE THREAD

**Issue by colin-axner** [danielmkarlsson/SuperClean#6]
I noticed when trying to update superclean from an older commit to the latest commit running quarks uninstall/install did not update my version. Going into the `downloaded-quarks` path and directly pulling the latest version of master into my local git repository and then rerunning uninstall/install worked. Some notes about this in the readme may be helpful, or maybe there is some command that can be executed from super collider that can automate this process?

##### Super Collider Version
SuperCollider 3.11.0-beta1

**Comment by danielmkarlsson** [comment]
This is a great idea. 
I will investigate and report back.

**Comment by danielmkarlsson** [comment]
I have updated the readme now to reflect how I do it. I felt like it was important to provide a solution which is not operating system specific. This solution is clunky, but better than nothing. I'll keep a lookout for a better way to do this.
