### ISSUE TITLE
Bug in examples? 's' should be 'snd', 'n' should be 'num'

### ISSUE THREAD

**Issue by tedthetrumpet** [danielmkarlsson/SuperClean#7]
I couldn't get any sound from the SuperClean examples in SuperCollider. Fixed it though: I think the problem is the examples are using keys called `s`and `n`, but in the `used-parameters.scd` file it seems those should actually be `snd` and `num`.  Maybe also in the examples `gain` should be `amp`?

**Comment by danielmkarlsson** [comment]
Hey Ted, long time no see!
Yes, quite right. My bad. I have fixed that now.
